const ActionTypes = {
    FETCH_ALL_EMPLOYEES: "FETCH_ALL_EMPLOYEES",
    FETCH_ALL_DEPARTMENTS: "FETCH_ALL_DEPARTMENTS",
    FETCH_ALL_LEAVE_APLLICATIONS: "FETCH_ALL_LEAVE_APLLICATIONS",
    FETCH_SINGLE_DEPARTMENT: "FETCH_SINGLE_DEPARTMENT",
    CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
    GET_EMPLOYEE_FROM_STATE: "GET_EMPLOYEE_FROM_STATE",
    GET_EMPLOYEE_FROM_DB: "GET_EMPLOYEE_FROM_DB",
    CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
    HIDE_LOADER: "HIDE_LOADER",
    FETCH_SINGLE_EMPLOYEE: "FETCH_SINGLE_EMPLOYEE",
    SHOW_LOADER: "SHOW_LOADER",
    GENERIC_ERROR: "GENERIC_ERROR",
    ERROR: "ERROR",
    NETWORK_ERROR: "NETWORK_ERROR",
}

export default ActionTypes